// English Partner Profile — Speaking & Personality Map
// Bilingual questionnaire data (English primary, Russian on demand).
//
// Question types:
//   checkbox      -> multiple choice, many answers
//   checkbox-max  -> multiple choice, limited by `max`
//   radio         -> single choice
//   short         -> short text answer
//   long          -> long text answer
//   scale         -> 1..5 rating with labels
//
// `hasOther: true` adds an optional free "Other" text field to a choice question.

const opt = (en, ru) => ({ en, ru })

export const activeVocabulary = [
  { en: 'speaking bottleneck', ru: 'узкое место в говорении' },
  { en: 'personal agency', ru: 'личная активная позиция' },
  { en: 'anchor reference', ru: 'опорный ориентир' },
  { en: 'strong consistency', ru: 'сильная регулярность' },
  { en: 'next action', ru: 'следующий шаг' },
  { en: 'learning style', ru: 'стиль обучения' },
  { en: 'comfort zone', ru: 'зона комфорта' },
  { en: 'conversation flow', ru: 'ход разговора' },
  { en: 'confidence level', ru: 'уровень уверенности' },
  { en: 'personal interests', ru: 'личные интересы' },
  { en: 'real-life topics', ru: 'темы из реальной жизни' },
  { en: 'AI-native learning', ru: 'обучение в стиле AI-native' },
  { en: 'structured answer', ru: 'структурированный ответ' },
  { en: 'growth area', ru: 'зона роста' },
]

export const sections = [
  {
    id: 'goal',
    title: { en: 'My English Goal', ru: 'Моя цель в английском' },
    tag: { en: 'personal agency', ru: 'личная активная позиция' },
    questions: [
      {
        id: 'q1',
        type: 'checkbox',
        hasOther: true,
        en: 'Why do you want to improve your spoken English?',
        ru: 'Зачем тебе улучшать разговорный английский?',
        options: [
          opt('I want to speak more confidently.', 'Хочу говорить увереннее.'),
          opt('I need English for studies.', 'Английский нужен для учёбы.'),
          opt('I need English for future work.', 'Английский нужен для будущей работы.'),
          opt('I want to travel and communicate.', 'Хочу путешествовать и общаться.'),
          opt(
            'I want to understand videos, podcasts, and social media.',
            'Хочу понимать видео, подкасты и соцсети.',
          ),
          opt('I want to sound smarter and more natural.', 'Хочу звучать умнее и естественнее.'),
          opt('I want to use English with AI tools.', 'Хочу использовать английский с ИИ-инструментами.'),
        ],
      },
      {
        id: 'q2',
        type: 'radio',
        en: 'What would be a good result for you after 1 month?',
        ru: 'Какой результат через 1 месяц был бы для тебя хорошим?',
        options: [
          opt('I can answer simple questions without panic.', 'Могу отвечать на простые вопросы без паники.'),
          opt('I can speak for 1 minute about myself.', 'Могу говорить о себе 1 минуту.'),
          opt('I can use 20–30 useful phrases.', 'Могу использовать 20–30 полезных фраз.'),
          opt('I can ask questions in English.', 'Могу задавать вопросы на английском.'),
          opt('I can understand the teacher better.', 'Лучше понимаю преподавателя.'),
          opt('I feel less blocked when I speak.', 'Меньше блока, когда говорю.'),
        ],
      },
      {
        id: 'q3',
        type: 'checkbox',
        en: 'What would be a strong result for you after 3 months?',
        ru: 'Какой сильный результат через 3 месяца был бы для тебя важен?',
        options: [
          opt('I can keep a simple conversation going.', 'Могу поддерживать простой разговор.'),
          opt('I can speak about my interests.', 'Могу говорить о своих интересах.'),
          opt('I can explain my opinion.', 'Могу объяснить своё мнение.'),
          opt('I can talk about studies, work, and plans.', 'Могу говорить об учёбе, работе и планах.'),
          opt('I can use active vocabulary naturally.', 'Могу естественно использовать активную лексику.'),
          opt('I can record short voice messages in English.', 'Могу записывать короткие голосовые на английском.'),
          opt('I can make short presentations.', 'Могу делать короткие презентации.'),
        ],
      },
    ],
  },
  {
    id: 'bottleneck',
    title: { en: 'My Speaking Bottleneck', ru: 'Моё узкое место в говорении' },
    tag: { en: 'speaking bottleneck', ru: 'узкое место в говорении' },
    questions: [
      {
        id: 'q4',
        type: 'checkbox',
        hasOther: true,
        en: 'What is your main speaking bottleneck?',
        ru: 'Какое главное узкое место мешает тебе говорить?',
        options: [
          opt('I know words, but I forget them when I speak.', 'Знаю слова, но забываю их, когда говорю.'),
          opt('I understand more than I can say.', 'Понимаю больше, чем могу сказать.'),
          opt('I am afraid of making mistakes.', 'Боюсь делать ошибки.'),
          opt('I need too much time to build a sentence.', 'Мне нужно слишком много времени, чтобы построить предложение.'),
          opt('I don’t know how to start my answer.', 'Не знаю, как начать ответ.'),
          opt('I don’t know how to continue the conversation.', 'Не знаю, как продолжить разговор.'),
          opt('I feel shy or blocked.', 'Стесняюсь или чувствую блок.'),
          opt('I don’t have enough active vocabulary.', 'Не хватает активной лексики.'),
          opt('I don’t know how to ask questions.', 'Не знаю, как задавать вопросы.'),
        ],
      },
      {
        id: 'q5',
        type: 'checkbox',
        en: 'When do you feel blocked most often?',
        ru: 'Когда ты чаще всего чувствуешь блок?',
        options: [
          opt('When the teacher asks me a direct question.', 'Когда преподаватель задаёт прямой вопрос.'),
          opt('When I need to answer quickly.', 'Когда нужно ответить быстро.'),
          opt('When I don’t know one word.', 'Когда не знаю одного слова.'),
          opt('When I compare myself with others.', 'Когда сравниваю себя с другими.'),
          opt('When I need to speak about myself.', 'Когда нужно говорить о себе.'),
          opt('When the topic is boring.', 'Когда тема скучная.'),
          opt('When I don’t understand the question.', 'Когда не понимаю вопрос.'),
          opt('When I need to speak without preparation.', 'Когда нужно говорить без подготовки.'),
        ],
      },
      {
        id: 'q6',
        type: 'short',
        en: 'Complete the sentence: “My speaking bottleneck is…”',
        ru: 'Закончи предложение: «Моё главное узкое место в говорении — это…»',
        placeholder: { en: 'My speaking bottleneck is…', ru: 'Моё узкое место в говорении — это…' },
      },
    ],
  },
  {
    id: 'personality',
    title: { en: 'My Personality in Communication', ru: 'Моя личность в общении' },
    tag: { en: 'conversation flow', ru: 'ход разговора' },
    questions: [
      {
        id: 'q7',
        type: 'radio',
        en: 'In a conversation, I usually prefer to…',
        ru: 'В разговоре я обычно предпочитаю…',
        options: [
          opt('Listen first, then speak.', 'Сначала слушать, потом говорить.'),
          opt('Speak quickly and react emotionally.', 'Говорить быстро и реагировать эмоционально.'),
          opt('Think carefully before answering.', 'Тщательно думать перед ответом.'),
          opt('Ask questions.', 'Задавать вопросы.'),
          opt('Give examples.', 'Приводить примеры.'),
          opt('Joke and make the conversation lighter.', 'Шутить и делать разговор легче.'),
          opt('Stay quiet until I feel comfortable.', 'Молчать, пока не почувствую себя комфортно.'),
        ],
      },
      {
        id: 'q8',
        type: 'checkbox',
        en: 'What kind of speaking partner feels comfortable for you?',
        ru: 'С каким собеседником тебе комфортнее говорить?',
        options: [
          opt('Patient and calm.', 'Терпеливый и спокойный.'),
          opt('Energetic and dynamic.', 'Энергичный и динамичный.'),
          opt('Funny and informal.', 'Весёлый и неформальный.'),
          opt('Structured and clear.', 'Структурный и чёткий.'),
          opt('Supportive and soft.', 'Поддерживающий и мягкий.'),
          opt('Direct and practical.', 'Прямой и практичный.'),
          opt('Creative and imaginative.', 'Творческий и с воображением.'),
          opt('Smart and challenging.', 'Умный и бросающий вызов.'),
        ],
      },
      {
        id: 'q9',
        type: 'checkbox',
        en: 'What helps you open up in conversation?',
        ru: 'Что помогает тебе раскрыться в разговоре?',
        options: [
          opt('Clear questions.', 'Чёткие вопросы.'),
          opt('Examples from the teacher.', 'Примеры от преподавателя.'),
          opt('Useful sentence starters.', 'Полезные фразы-стартеры.'),
          opt('A friendly atmosphere.', 'Дружелюбная атмосфера.'),
          opt('Interesting topics.', 'Интересные темы.'),
          opt('Time to think.', 'Время подумать.'),
          opt('Visual prompts.', 'Визуальные подсказки.'),
          opt('Role-play.', 'Ролевые игры.'),
          opt('Speaking frames.', 'Речевые шаблоны.'),
          opt('Teacher’s personal example first.', 'Сначала личный пример преподавателя.'),
        ],
      },
    ],
  },
  {
    id: 'interests',
    title: { en: 'My Interests and Real-Life Topics', ru: 'Мои интересы и темы из жизни' },
    tag: { en: 'real-life topics', ru: 'темы из реальной жизни' },
    questions: [
      {
        id: 'q10',
        type: 'checkbox',
        hasOther: true,
        en: 'Which topics can you discuss for a long time in Russian?',
        ru: 'Какие темы ты можешь долго обсуждать на русском?',
        options: [
          opt('Music', 'Музыка'),
          opt('Films and series', 'Фильмы и сериалы'),
          opt('Art and design', 'Искусство и дизайн'),
          opt('Fashion and style', 'Мода и стиль'),
          opt('Social media', 'Соцсети'),
          opt('Psychology', 'Психология'),
          opt('Relationships and friendship', 'Отношения и дружба'),
          opt('Travel', 'Путешествия'),
          opt('Food and lifestyle', 'Еда и образ жизни'),
          opt('AI and technology', 'ИИ и технологии'),
          opt('Future career', 'Будущая карьера'),
          opt('Education', 'Образование'),
          opt('Money and independence', 'Деньги и независимость'),
          opt('Creativity', 'Творчество'),
          opt('Games', 'Игры'),
          opt('Books', 'Книги'),
          opt('Sport', 'Спорт'),
        ],
      },
      {
        id: 'q11',
        type: 'checkbox',
        hasOther: true,
        en: 'Which topics are boring or uncomfortable for you?',
        ru: 'Какие темы тебе скучны или некомфортны?',
        options: [
          opt('Politics', 'Политика'),
          opt('Sport', 'Спорт'),
          opt('Business', 'Бизнес'),
          opt('Science', 'Наука'),
          opt('Personal questions', 'Личные вопросы'),
          opt('School topics', 'Школьные темы'),
          opt('Grammar-only tasks', 'Задания только по грамматике'),
          opt('Abstract topics', 'Абстрактные темы'),
          opt('News', 'Новости'),
        ],
      },
      {
        id: 'q12',
        type: 'checkbox-max',
        max: 3,
        en: 'Choose 3 topics for our first speaking lessons.',
        ru: 'Выбери 3 темы для первых разговорных занятий.',
        options: [
          opt('My personality and interests', 'Моя личность и интересы'),
          opt('My daily life', 'Моя повседневная жизнь'),
          opt('My future career', 'Моя будущая карьера'),
          opt('My style and taste', 'Мой стиль и вкус'),
          opt('My favourite content', 'Мой любимый контент'),
          opt('AI in everyday life', 'ИИ в повседневной жизни'),
          opt('Friendship and communication', 'Дружба и общение'),
          opt('Confidence and personal agency', 'Уверенность и личная активная позиция'),
          opt('Study routine', 'Учебная рутина'),
          opt('Creative projects', 'Творческие проекты'),
          opt('Travel situations', 'Ситуации в путешествиях'),
          opt('Modern vocabulary', 'Современная лексика'),
        ],
      },
    ],
  },
  {
    id: 'style',
    title: { en: 'My Learning Style', ru: 'Мой стиль обучения' },
    tag: { en: 'learning style', ru: 'стиль обучения' },
    questions: [
      {
        id: 'q13',
        type: 'checkbox',
        en: 'I learn better when…',
        ru: 'Я лучше учусь, когда…',
        options: [
          opt('I see examples first.', 'Сначала вижу примеры.'),
          opt('I repeat after the teacher.', 'Повторяю за преподавателем.'),
          opt('I speak immediately.', 'Говорю сразу.'),
          opt('I write before speaking.', 'Пишу перед тем, как говорить.'),
          opt('I use pictures or cards.', 'Использую картинки или карточки.'),
          opt('I have a clear structure.', 'У меня есть чёткая структура.'),
          opt('I play roles.', 'Играю роли.'),
          opt('I get correction after speaking.', 'Получаю исправления после ответа.'),
          opt('I work with short phrases.', 'Работаю с короткими фразами.'),
          opt('I connect English with my real life.', 'Связываю английский с реальной жизнью.'),
        ],
      },
      {
        id: 'q14',
        type: 'radio',
        en: 'What is your best anchor reference for learning?',
        ru: 'Какой опорный формат тебе больше помогает?',
        options: [
          opt('A model answer from the teacher.', 'Образцовый ответ преподавателя.'),
          opt('A short dialogue.', 'Короткий диалог.'),
          opt('A visual card.', 'Визуальная карточка.'),
          opt('A sentence frame.', 'Речевой шаблон.'),
          opt('A real-life situation.', 'Ситуация из реальной жизни.'),
          opt('A video example.', 'Пример из видео.'),
          opt('A list of useful phrases.', 'Список полезных фраз.'),
          opt('A personal story.', 'Личная история.'),
        ],
      },
      {
        id: 'q15',
        type: 'checkbox',
        en: 'How do you prefer to practise new vocabulary?',
        ru: 'Как тебе удобнее отрабатывать новую лексику?',
        options: [
          opt('In short dialogues.', 'В коротких диалогах.'),
          opt('In personal examples.', 'В личных примерах.'),
          opt('In voice messages.', 'В голосовых сообщениях.'),
          opt('In mini-presentations.', 'В мини-презентациях.'),
          opt('In written answers first.', 'Сначала в письменных ответах.'),
          opt('In role-play.', 'В ролевых играх.'),
          opt('In question-answer practice.', 'В практике «вопрос-ответ».'),
          opt('In story format.', 'В формате истории.'),
          opt('With Russian support first.', 'Сначала с поддержкой на русском.'),
          opt('Without Russian support if possible.', 'Без поддержки на русском, если возможно.'),
        ],
      },
    ],
  },
  {
    id: 'agency',
    title: { en: 'Personal Agency', ru: 'Личная активная позиция' },
    tag: { en: 'personal agency', ru: 'личная активная позиция' },
    questions: [
      {
        id: 'q16',
        type: 'checkbox',
        en: 'Personal agency means that I…',
        ru: 'Личная активная позиция означает, что я…',
        options: [
          opt('Take small steps even when I feel unsure.', 'Делаю маленькие шаги, даже когда не уверен(а).'),
          opt('Ask questions when I don’t understand.', 'Задаю вопросы, когда не понимаю.'),
          opt('Practise a little between lessons.', 'Немного практикуюсь между занятиями.'),
          opt('Try to speak even with mistakes.', 'Пробую говорить даже с ошибками.'),
          opt('Track my progress.', 'Отслеживаю свой прогресс.'),
          opt('Choose topics that matter to me.', 'Выбираю важные для себя темы.'),
          opt('Use AI or online tools to learn better.', 'Использую ИИ или онлайн-инструменты, чтобы учиться лучше.'),
          opt('Don’t wait for perfect confidence.', 'Не жду идеальной уверенности.'),
          opt('Build strong consistency.', 'Выстраиваю сильную регулярность.'),
        ],
      },
      {
        id: 'q17',
        type: 'radio',
        en: 'Which “next action” feels realistic for you this week?',
        ru: 'Какой следующий шаг на этой неделе для тебя реалистичен?',
        options: [
          opt('Record one 30-second voice message.', 'Записать одно голосовое на 30 секунд.'),
          opt('Learn 5 useful phrases.', 'Выучить 5 полезных фраз.'),
          opt('Answer 3 questions in English.', 'Ответить на 3 вопроса на английском.'),
          opt('Watch one short video in English.', 'Посмотреть одно короткое видео на английском.'),
          opt('Prepare one personal story.', 'Подготовить одну личную историю.'),
          opt('Practise one dialogue.', 'Отработать один диалог.'),
          opt('Ask the teacher 3 questions in English.', 'Задать преподавателю 3 вопроса на английском.'),
          opt('Repeat one speaking frame every day.', 'Повторять один речевой шаблон каждый день.'),
        ],
      },
      {
        id: 'q18',
        type: 'short',
        en: 'Complete the sentence: “My next action is…”',
        ru: 'Закончи предложение: «Мой следующий шаг — это…»',
        placeholder: { en: 'My next action is…', ru: 'Мой следующий шаг — это…' },
      },
    ],
  },
  {
    id: 'confidence',
    title: { en: 'Speaking Confidence', ru: 'Уверенность в говорении' },
    tag: { en: 'confidence level', ru: 'уровень уверенности' },
    questions: [
      {
        id: 'q19',
        type: 'scale',
        en: 'Rate your speaking confidence today.',
        ru: 'Оцени свою уверенность в говорении сейчас.',
        labels: {
          en: {
            1: 'I feel blocked.',
            2: 'I can answer only very simple questions.',
            3: 'I can speak with support.',
            4: 'I can speak, but I need more fluency.',
            5: 'I feel confident.',
          },
          ru: {
            1: 'Чувствую блок.',
            2: 'Могу отвечать только на очень простые вопросы.',
            3: 'Могу говорить с поддержкой.',
            4: 'Могу говорить, но нужна беглость.',
            5: 'Чувствую уверенность.',
          },
        },
      },
      {
        id: 'q20',
        type: 'checkbox',
        en: 'What would make you feel more confident?',
        ru: 'Что помогло бы тебе чувствовать себя увереннее?',
        options: [
          opt('More teacher examples.', 'Больше примеров от преподавателя.'),
          opt('More useful phrases.', 'Больше полезных фраз.'),
          opt('Less pressure.', 'Меньше давления.'),
          opt('More speaking time.', 'Больше времени на говорение.'),
          opt('Clear correction.', 'Чёткое исправление ошибок.'),
          opt('Pronunciation practice.', 'Практика произношения.'),
          opt('Topics that I like.', 'Темы, которые мне нравятся.'),
          opt('Short preparation time.', 'Короткое время на подготовку.'),
          opt('Role-play.', 'Ролевые игры.'),
          opt('Repeating the same structure several times.', 'Повторение одной структуры несколько раз.'),
        ],
      },
      {
        id: 'q21',
        type: 'radio',
        en: 'What type of correction is comfortable for you?',
        ru: 'Какой формат исправления ошибок тебе комфортен?',
        options: [
          opt('Correct me immediately.', 'Исправляй меня сразу.'),
          opt('Correct me after I finish speaking.', 'Исправляй после того, как я закончу.'),
          opt('Write my mistakes in a correction board.', 'Записывай мои ошибки на доску исправлений.'),
          opt('Give me a better version of my sentence.', 'Дай мне улучшенную версию моего предложения.'),
          opt('Correct only important mistakes.', 'Исправляй только важные ошибки.'),
          opt('Mix correction with positive feedback.', 'Совмещай исправления с позитивной обратной связью.'),
        ],
      },
    ],
  },
  {
    id: 'structure',
    title: { en: 'Structured Speaking', ru: 'Структурированная речь' },
    tag: { en: 'structured answer', ru: 'структурированный ответ' },
    questions: [
      {
        id: 'q22',
        type: 'radio',
        en: 'Which answer structure feels easiest for you?',
        ru: 'Какая структура ответа кажется тебе самой удобной?',
        options: [
          opt('Point → Reason → Example', 'Мысль → Причина → Пример'),
          opt('Problem → Solution → Next action', 'Проблема → Решение → Следующий шаг'),
          opt('Opinion → Example → Question back', 'Мнение → Пример → Встречный вопрос'),
          opt('Situation → Feeling → Action', 'Ситуация → Чувство → Действие'),
          opt('Past → Present → Future', 'Прошлое → Настоящее → Будущее'),
          opt('I don’t know yet. I need an anchor reference.', 'Пока не знаю. Мне нужен опорный ориентир.'),
        ],
      },
      {
        id: 'q23',
        type: 'checkbox',
        en: 'Choose the sentence starters you want to practise.',
        ru: 'Выбери фразы-стартеры, которые хочешь отработать.',
        options: [
          opt('My main point is…', 'Моя главная мысль…'),
          opt('The reason is…', 'Причина в том, что…'),
          opt('For example…', 'Например…'),
          opt('In my opinion…', 'По моему мнению…'),
          opt('I agree because…', 'Я согласен(а), потому что…'),
          opt('I’m not sure, but…', 'Я не уверен(а), но…'),
          opt('My next action is…', 'Мой следующий шаг…'),
          opt('The main bottleneck is…', 'Главное узкое место…'),
          opt('What about you?', 'А ты как?'),
          opt('Could you explain that again?', 'Можешь объяснить ещё раз?'),
        ],
      },
      {
        id: 'q24',
        type: 'long',
        en: 'Build your first structured answer.',
        ru: 'Собери свой первый структурированный ответ.',
        prompt: {
          en: 'Use this frame:\nMy main point is that…\nThe reason is…\nFor example…\nMy next action is…\nWhat about you?',
          ru: 'Используй шаблон:\nMy main point is that… (Моя главная мысль…)\nThe reason is… (Причина в том, что…)\nFor example… (Например…)\nMy next action is… (Мой следующий шаг…)\nWhat about you? (А ты как?)',
        },
        placeholder: { en: 'My main point is that…', ru: 'My main point is that…' },
      },
    ],
  },
  {
    id: 'ai',
    title: { en: 'AI-Native Learning', ru: 'Обучение в стиле AI-native' },
    tag: { en: 'AI-native learning', ru: 'обучение в стиле AI-native' },
    questions: [
      {
        id: 'q25',
        type: 'radio',
        en: 'Do you use AI tools for learning?',
        ru: 'Используешь ли ты ИИ-инструменты для обучения?',
        options: [
          opt('Yes, often.', 'Да, часто.'),
          opt('Sometimes.', 'Иногда.'),
          opt('I tried once or twice.', 'Пробовал(а) раз или два.'),
          opt('Not yet, but I am interested.', 'Пока нет, но мне интересно.'),
          opt('No, I don’t want to.', 'Нет, не хочу.'),
        ],
      },
      {
        id: 'q26',
        type: 'checkbox',
        en: 'How could AI help your English learning?',
        ru: 'Как ИИ может помочь тебе в английском?',
        options: [
          opt('Create speaking topics.', 'Создавать темы для говорения.'),
          opt('Explain grammar simply.', 'Просто объяснять грамматику.'),
          opt('Give examples.', 'Давать примеры.'),
          opt('Check my writing.', 'Проверять моё письмо.'),
          opt('Help me prepare dialogues.', 'Помогать готовить диалоги.'),
          opt('Generate vocabulary.', 'Генерировать лексику.'),
          opt('Help with pronunciation.', 'Помогать с произношением.'),
          opt('Make learning more personalised.', 'Делать обучение более персональным.'),
          opt('Create mini-tests.', 'Создавать мини-тесты.'),
          opt('I don’t know yet.', 'Пока не знаю.'),
        ],
      },
      {
        id: 'q27',
        type: 'short',
        en: 'Complete the sentence: “I want to become more AI-native because…”',
        ru: 'Закончи предложение: «Я хочу стать более AI-native, потому что…»',
        placeholder: {
          en: 'I want to become more AI-native because…',
          ru: 'Я хочу стать более AI-native, потому что…',
        },
      },
    ],
  },
]

export const totalQuestions = sections.reduce((sum, s) => sum + s.questions.length, 0)
